/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GanttChartPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// GanttChartView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_GANTT = "gantt-chart-view";
var GanttChartView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_GANTT;
  }
  getDisplayText() {
    return "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8";
  }
  getIcon() {
    return "calendar-glyph";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("gantt-view-container");
    this.createHeader(container);
    this.createAddTaskButton(container);
    this.createGanttTable(container);
  }
  createHeader(container) {
    const header = container.createDiv({ cls: "gantt-header" });
    header.createEl("h4", { text: "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8", cls: "gantt-title" });
  }
  createAddTaskButton(container) {
    const buttonContainer = container.createDiv({ cls: "gantt-button-container" });
    const button = buttonContainer.createEl("button", {
      text: "+ \u65B0\u3057\u3044\u30BF\u30B9\u30AF",
      cls: "add-task-button"
    });
    button.addEventListener("click", () => {
      const today = new Date();
      const todayStr = this.formatDate(today);
      const nextWeek = new Date(today);
      nextWeek.setDate(nextWeek.getDate() + 7);
      const nextWeekStr = this.formatDate(nextWeek);
      this.plugin.settings.tasks.push({
        name: "\u65B0\u3057\u3044\u30BF\u30B9\u30AF",
        startDate: todayStr,
        endDate: nextWeekStr
      });
      this.plugin.saveSettings();
      this.refresh();
    });
  }
  createGanttTable(container) {
    const wrapper = container.createDiv({ cls: "gantt-table-wrapper" });
    const table = wrapper.createEl("table", { cls: "gantt-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "\u30BF\u30B9\u30AF\u540D", cls: "gantt-fixed-column" });
    headerRow.createEl("th", { text: "\u958B\u59CB\u65E5", cls: "gantt-fixed-column gantt-date-header" });
    headerRow.createEl("th", { text: "\u7D42\u4E86\u65E5", cls: "gantt-fixed-column gantt-date-header" });
    headerRow.createEl("th", { text: "\u64CD\u4F5C", cls: "gantt-fixed-column gantt-action-header" });
    this.addCalendarHeaders(headerRow);
    const tbody = table.createEl("tbody");
    for (const task of this.plugin.settings.tasks) {
      this.createTaskRow(tbody, task);
    }
  }
  addCalendarHeaders(headerRow) {
    var _a;
    const { startDate, endDate } = this.calculateDateRange();
    const dates = this.generateDateArray(startDate, endDate);
    const monthRow = (_a = headerRow.parentElement) == null ? void 0 : _a.createEl("tr", { cls: "gantt-month-row" });
    if (monthRow) {
      monthRow.createEl("th", { cls: "gantt-fixed-column" });
      monthRow.createEl("th", { cls: "gantt-fixed-column" });
      monthRow.createEl("th", { cls: "gantt-fixed-column" });
      monthRow.createEl("th", { cls: "gantt-fixed-column" });
      let currentMonth = -1;
      let monthColspan = 0;
      let monthCell = null;
      for (let i = 0; i < dates.length; i++) {
        const date = dates[i];
        const month = date.getMonth();
        const year = date.getFullYear();
        if (month !== currentMonth || i > 0 && dates[i - 1].getFullYear() !== year) {
          if (monthCell) {
            monthCell.setAttribute("colspan", monthColspan.toString());
          }
          currentMonth = month;
          monthColspan = 1;
          monthCell = monthRow.createEl("th", {
            cls: "gantt-month-header",
            text: `${year}/${String(month + 1).padStart(2, "0")}`
          });
        } else {
          monthColspan++;
        }
      }
      if (monthCell) {
        monthCell.setAttribute("colspan", monthColspan.toString());
      }
    }
    headerRow.createEl("th", { cls: "gantt-spacer" });
    const today = this.getToday();
    for (const date of dates) {
      const day = date.getDate();
      const dayOfWeek = date.getDay();
      const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
      const isToday = date.getTime() === today.getTime();
      headerRow.createEl("th", {
        cls: `gantt-date-header ${isWeekend ? "gantt-weekend" : ""} ${isToday ? "gantt-today" : ""}`,
        text: day.toString()
      });
    }
  }
  createTaskRow(tbody, task) {
    const row = tbody.createEl("tr", { cls: "gantt-task-row" });
    const nameCell = row.createEl("td", { cls: "gantt-editable gantt-fixed-column" });
    nameCell.contentEditable = "true";
    nameCell.textContent = task.name;
    nameCell.addEventListener("blur", () => {
      task.name = nameCell.textContent || "";
      this.plugin.saveSettings();
    });
    nameCell.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        nameCell.blur();
      }
    });
    const startCell = row.createEl("td", { cls: "gantt-editable gantt-date-cell gantt-fixed-column" });
    startCell.contentEditable = "true";
    startCell.textContent = task.startDate;
    startCell.addEventListener("blur", () => {
      task.startDate = startCell.textContent || "";
      this.plugin.saveSettings();
      this.refresh();
    });
    startCell.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        startCell.blur();
      }
    });
    const endCell = row.createEl("td", { cls: "gantt-editable gantt-date-cell gantt-fixed-column" });
    endCell.contentEditable = "true";
    endCell.textContent = task.endDate;
    endCell.addEventListener("blur", () => {
      task.endDate = endCell.textContent || "";
      this.plugin.saveSettings();
      this.refresh();
    });
    endCell.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        endCell.blur();
      }
    });
    const actionCell = row.createEl("td", { cls: "gantt-action-cell gantt-fixed-column" });
    const deleteBtn = actionCell.createEl("button", {
      text: "\u2715",
      cls: "delete-task-button"
    });
    deleteBtn.addEventListener("click", () => {
      const index = this.plugin.settings.tasks.indexOf(task);
      if (index > -1) {
        this.plugin.settings.tasks.splice(index, 1);
        this.plugin.saveSettings();
        this.refresh();
      }
    });
    this.addGanttCells(row, task);
  }
  addGanttCells(row, task) {
    const { startDate, endDate } = this.calculateDateRange();
    const dates = this.generateDateArray(startDate, endDate);
    const today = this.getToday();
    const taskStart = this.parseDate(task.startDate);
    const taskEnd = this.parseDate(task.endDate);
    if (!taskStart || !taskEnd)
      return;
    for (let i = 0; i < dates.length; i++) {
      const date = dates[i];
      const dayOfWeek = date.getDay();
      const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
      const isMonthBoundary = date.getDate() === 1 && i > 0;
      const isToday = date.getTime() === today.getTime();
      const cell = row.createEl("td", {
        cls: `gantt-date-cell ${isWeekend ? "gantt-weekend" : ""} ${isMonthBoundary ? "gantt-month-boundary" : ""} ${isToday ? "gantt-today" : ""}`
      });
      const dateTime = date.getTime();
      const taskStartTime = taskStart.getTime();
      const taskEndTime = taskEnd.getTime();
      if (dateTime >= taskStartTime && dateTime <= taskEndTime) {
        const isFirstDay = dateTime === taskStartTime;
        const isLastDay = dateTime === taskEndTime;
        cell.createEl("div", {
          cls: `gantt-bar ${isFirstDay ? "gantt-bar-start" : ""} ${isLastDay ? "gantt-bar-end" : ""}`
        });
      }
    }
  }
  calculateDateRange() {
    const today = this.getToday();
    if (this.plugin.settings.tasks.length === 0) {
      return { startDate: today, endDate: today };
    }
    const startDate = new Date(today);
    let maxDate = today;
    for (const task of this.plugin.settings.tasks) {
      const taskEnd = this.parseDate(task.endDate);
      if (taskEnd && taskEnd >= today && taskEnd > maxDate) {
        maxDate = taskEnd;
      }
    }
    const endDate = new Date(maxDate.getFullYear(), maxDate.getMonth() + 1, 0);
    return { startDate, endDate };
  }
  generateDateArray(startDate, endDate) {
    const dates = [];
    const current = new Date(startDate);
    while (current <= endDate) {
      dates.push(new Date(current));
      current.setDate(current.getDate() + 1);
    }
    return dates;
  }
  getToday() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return today;
  }
  parseDate(dateStr) {
    dateStr = dateStr.trim();
    const match = dateStr.match(/(\d{4})[-/](\d{1,2})[-/](\d{1,2})/);
    if (match) {
      const year = parseInt(match[1]);
      const month = parseInt(match[2]) - 1;
      const day = parseInt(match[3]);
      const date = new Date(year, month, day);
      date.setHours(0, 0, 0, 0);
      return date;
    }
    return null;
  }
  formatDate(date) {
    const year = date.getFullYear();
    const month = String(date.getMonth() + 1).padStart(2, "0");
    const day = String(date.getDate()).padStart(2, "0");
    return `${year}/${month}/${day}`;
  }
  refresh() {
    this.onOpen();
  }
  async onClose() {
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  tasks: [
    {
      name: "\u30BF\u30B9\u30AF1",
      startDate: "2025/12/07",
      endDate: "2025/12/10"
    },
    {
      name: "\u30BF\u30B9\u30AF2",
      startDate: "2025/12/09",
      endDate: "2025/12/15"
    },
    {
      name: "\u30BF\u30B9\u30AF3",
      startDate: "2025/12/13",
      endDate: "2025/12/20"
    }
  ]
};
var GanttChartPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_GANTT,
      (leaf) => new GanttChartView(leaf, this)
    );
    this.addRibbonIcon("calendar-glyph", "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8", () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-gantt-chart",
      name: "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u3092\u958B\u304F",
      callback: () => {
        this.activateView();
      }
    });
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_GANTT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      const rightLeaf = workspace.getRightLeaf(false);
      if (rightLeaf) {
        leaf = rightLeaf;
        await leaf.setViewState({
          type: VIEW_TYPE_GANTT,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  onunload() {
  }
};
