/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => GanttChartPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var GanttChartPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("Loading Gantt Chart Plugin");
    this.registerMarkdownPostProcessor((el, ctx) => {
      const info = ctx.getSectionInfo(el);
      if (!info)
        return;
      const abstractFile = this.app.vault.getAbstractFileByPath(ctx.sourcePath);
      if (!abstractFile)
        return;
      if (!("extension" in abstractFile))
        return;
      const file = abstractFile;
      this.app.vault.read(file).then((content) => {
        const frontmatterMatch = content.match(/^---\s*\n([\s\S]*?)\n---/);
        if (!frontmatterMatch)
          return;
        const frontmatter = frontmatterMatch[1];
        if (!frontmatter.includes("gantt: true") && !frontmatter.includes("gantt:true"))
          return;
        const ganttContent = content.replace(/^---\s*\n[\s\S]*?\n---\s*\n/, "").trim();
        el.empty();
        this.renderGanttChart(ganttContent, el, ctx);
      });
    });
  }
  onunload() {
    console.log("Unloading Gantt Chart Plugin");
  }
  /**
   * Get today's date at midnight
   */
  getToday() {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return today;
  }
  /**
   * Parse gantt data from source text
   * Format: タスク名 | 開始日 | 終了日
   * Date format: YYYY/MM/DD or YYYY-MM-DD
   */
  parseGanttData(source) {
    const tasks = [];
    const lines = source.trim().split("\n");
    const today = this.getToday();
    for (const line of lines) {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith("#"))
        continue;
      const parts = trimmedLine.split("|").map((p) => p.trim());
      if (parts.length !== 3)
        continue;
      const [name, startDateStr, endDateStr] = parts;
      const startDate = this.parseDate(startDateStr);
      const endDate = this.parseDate(endDateStr);
      if (startDate && endDate) {
        if (endDate >= today) {
          tasks.push({ name, startDate, endDate });
        }
      }
    }
    return tasks;
  }
  /**
   * Parse date string in various formats
   */
  parseDate(dateStr) {
    dateStr = dateStr.trim();
    const match = dateStr.match(/(\d{4})[-/](\d{1,2})[-/](\d{1,2})/);
    if (match) {
      const year = parseInt(match[1]);
      const month = parseInt(match[2]) - 1;
      const day = parseInt(match[3]);
      const date = new Date(year, month, day);
      date.setHours(0, 0, 0, 0);
      return date;
    }
    return null;
  }
  /**
   * Calculate the date range for the gantt chart
   * Always starts from today
   */
  calculateDateRange(tasks) {
    const today = this.getToday();
    if (tasks.length === 0) {
      return { startDate: today, endDate: today };
    }
    const startDate = new Date(today);
    let maxDate = tasks[0].endDate;
    for (const task of tasks) {
      if (task.endDate > maxDate)
        maxDate = task.endDate;
    }
    const endDate = new Date(maxDate.getFullYear(), maxDate.getMonth() + 1, 0);
    return { startDate, endDate };
  }
  /**
   * Generate array of dates between start and end
   */
  generateDateArray(startDate, endDate) {
    const dates = [];
    const current = new Date(startDate);
    while (current <= endDate) {
      dates.push(new Date(current));
      current.setDate(current.getDate() + 1);
    }
    return dates;
  }
  /**
   * Render the gantt chart
   */
  renderGanttChart(source, el, ctx) {
    const tasks = this.parseGanttData(source);
    if (tasks.length === 0) {
      el.createEl("div", {
        text: "\u30AC\u30F3\u30C8\u30C1\u30E3\u30FC\u30C8\u306B\u30BF\u30B9\u30AF\u304C\u3042\u308A\u307E\u305B\u3093\u3002\u5F62\u5F0F: \u30BF\u30B9\u30AF\u540D | \u958B\u59CB\u65E5 | \u7D42\u4E86\u65E5",
        cls: "gantt-error"
      });
      return;
    }
    const { startDate, endDate } = this.calculateDateRange(tasks);
    const dates = this.generateDateArray(startDate, endDate);
    const container = el.createEl("div", { cls: "gantt-chart-container gantt-chart-fullpage" });
    const table = container.createEl("table", { cls: "gantt-chart-table" });
    this.renderHeader(table, dates);
    this.renderTaskRows(table, tasks, dates, startDate);
  }
  /**
   * Render calendar header
   */
  renderHeader(table, dates) {
    const thead = table.createEl("thead");
    const monthRow = thead.createEl("tr", { cls: "gantt-month-row" });
    monthRow.createEl("th", { cls: "gantt-task-header", text: "\u30BF\u30B9\u30AF" });
    let currentMonth = -1;
    let monthColspan = 0;
    let monthCell = null;
    for (let i = 0; i < dates.length; i++) {
      const date = dates[i];
      const month = date.getMonth();
      const year = date.getFullYear();
      if (month !== currentMonth || i > 0 && dates[i - 1].getFullYear() !== year) {
        if (monthCell) {
          monthCell.setAttribute("colspan", monthColspan.toString());
        }
        currentMonth = month;
        monthColspan = 1;
        monthCell = monthRow.createEl("th", {
          cls: "gantt-month-header",
          text: `${year}/${String(month + 1).padStart(2, "0")}`
        });
      } else {
        monthColspan++;
      }
    }
    if (monthCell) {
      monthCell.setAttribute("colspan", monthColspan.toString());
    }
    const dateRow = thead.createEl("tr", { cls: "gantt-date-row" });
    dateRow.createEl("th", { cls: "gantt-task-header-date" });
    const today = this.getToday();
    for (const date of dates) {
      const day = date.getDate();
      const dayOfWeek = date.getDay();
      const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
      const isToday = date.getTime() === today.getTime();
      dateRow.createEl("th", {
        cls: `gantt-date-header ${isWeekend ? "gantt-weekend" : ""} ${isToday ? "gantt-today" : ""}`,
        text: day.toString()
      });
    }
  }
  /**
   * Render task rows with gantt bars
   */
  renderTaskRows(table, tasks, dates, chartStartDate) {
    const tbody = table.createEl("tbody");
    const today = this.getToday();
    for (const task of tasks) {
      const row = tbody.createEl("tr", { cls: "gantt-task-row" });
      row.createEl("td", { cls: "gantt-task-name", text: task.name });
      for (let i = 0; i < dates.length; i++) {
        const date = dates[i];
        const dayOfWeek = date.getDay();
        const isWeekend = dayOfWeek === 0 || dayOfWeek === 6;
        const isMonthBoundary = date.getDate() === 1 && i > 0;
        const isToday = date.getTime() === today.getTime();
        const cell = row.createEl("td", {
          cls: `gantt-date-cell ${isWeekend ? "gantt-weekend" : ""} ${isMonthBoundary ? "gantt-month-boundary" : ""} ${isToday ? "gantt-today" : ""}`
        });
        const dateTime = date.getTime();
        const taskStartTime = task.startDate.getTime();
        const taskEndTime = task.endDate.getTime();
        if (dateTime >= taskStartTime && dateTime <= taskEndTime) {
          const isFirstDay = dateTime === taskStartTime;
          const isLastDay = dateTime === taskEndTime;
          cell.createEl("div", {
            cls: `gantt-bar ${isFirstDay ? "gantt-bar-start" : ""} ${isLastDay ? "gantt-bar-end" : ""}`
          });
        }
      }
    }
  }
};
